### ISSUE TITLE
Python error when using cleaner tool

### ISSUE THREAD

**Issue by dsavary** [3nids/intersectit#11]
Hi Denis, I found this error when I use the cleaner tool of "intersect It" to erase all the features in the memory layer. 

> AttributeError: 'builtin_function_or_method' object has no attribute 'refresh' 
Traceback (most recent call last):
  File "C:/Users/Daniel/.qgis2/python/plugins\intersectit\intersectit_plugin.py", line 190, in clean_memory_layers
    MemoryLayers(self.iface).clean_layers()
  File "C:/Users/Daniel/.qgis2/python/plugins\intersectit\core\memory_layers.py", line 60, in clean_layers
    self.iface.mapCanvas.refresh()
AttributeError: 'builtin_function_or_method' object has no attribute 'refresh'

> Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.18.6 Las Palmas, 5f369b0 

Do you have an idea how to fix this error ?

**Comment by SteveLowman** [comment]
I confirm the same error is happening with QGIS 2.14.17

**Comment by 3nids** [comment]
should be fixed in 3.5.4
thanks for reporting
